- name: add nginx apt-key
  become: yes
  apt_key:
    url: "{{ nginx_repo_key }}"

- name: add nginx apt repository
  become: yes
  apt_repository:
    repo: "{{ nginx_repo_url }}"
    update_cache: yes

- name: install nginx
  become: yes
  apt:
    name: nginx
