---
- name: mail - Setup mail alerts
  template:
    src: mail.conf.j2
    dest: {{ monit_includes }}/mail
    owner: root
    group: root
    mode: 0644
  notify: restart monit
  when: monit_mail_enabled
