- name: Ensure Monit apt repository exists
  apt_repository:
    repo: "deb http://ftp.de.debian.org/debian buster-backports main"
    state: present

- name: Install monit
  package:
    name: monit
    state: present

- include: config.yml
  tags: monit_config

- include: monitors.yml
  tags: monit_monitors

- include: service.yml
  tags: monit_service
