---
- name: Configure php-fpm pool
  become: true
  template:
    src: pool.conf.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/{{ short_username }}.conf
  notify:
    - check php-fpm config
    - reload php-fpm
