---
- name: install dependencies
  apt:
    name: "{{item}}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: "{{docker_debian_key_url}}"
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb {{docker_debian_install_url}} bionic stable
    state: present

- name: install docker
  apt:
    name: "{{item}}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - docker-compose
    - containerd.io

- name: check docker service started
  service:
    name: docker
    state: started
    enabled: yes