---
- name: Create user 'deploy'
  become : true
  user:
    name: deploy
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519

- name: Create /app folder and assign rights to deploy
  become: true
  file:
    path: /app
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'
